### ISSUE TITLE
Page not loading after installation

### ISSUE THREAD

**Issue by peptolab** [nilsenpaul/craft-sequentialedit#1]
Installed from Plugin Store on Craft CMS 3 and tried to multiple edit 2 entries.

Results in an infinite looped redirect on multiple browsers.

Safari reports:

XMLHttpRequest cannot load http://[my server]/index.php?p=admin/actions/users/get-remaining-session-time&dontExtendSession=1 due to access control checks.
send - jquery.jsL9566
ajax - jquery.js:9173
checkRemainingSessionTime - Craft.js:9206

[web.log](https://github.com/nilsenpaul/craft-sequentialedit/files/2158044/web.log)

Server seems to be repeatedly redirecting to the same page even despite having just logged in.

**Comment by nilsenpaul** [comment]
The log only shows a request for the getRemainingSessionTime action, which doesn't have anything to do with this plugin. To what page do you get redirected?

**Comment by nilsenpaul** [comment]
Fixed by https://github.com/nilsenpaul/craft-sequentialedit/commit/1b91b4254e6b8419042b04fb5f7447e4f9056a38.
