### ISSUE TITLE
With plugin enabled, "My Account" is not available.

### ISSUE THREAD

**Issue by matthillco** [nilsenpaul/craft-sequentialedit#11]
If the plugin is enabled, the "My Account" option is not available. The "My Account" page breaks with the following error:

`PHP Notice – yii\base\ErrorException - Undefined index: element`

I've tried this with all other plugins disabled, running Craft Solo 3.4.4 and plugin version 1.0.8.3.

Stack trace is here if helpful: https://pastebin.com/vVixkQBH

**Comment by nilsenpaul** [comment]
Thanks @matthillco, it's fixed in 1.0.8.4!

**Comment by matthillco** [comment]
Great, thank you. I almost never go into My Account, but needed to on this project and noticed the issue. I disabled plugins one by one to see if any of them were connected. Glad to be some help :)
