### ISSUE TITLE
Database error when trying to install

### ISSUE THREAD

**Issue by keithmancuso** [nilsenpaul/craft-sequentialedit#3]
<img width="1289" alt="screenshot 2018-08-25 16 02 50" src="https://user-images.githubusercontent.com/275913/44622115-5929ec00-a880-11e8-841a-33d6fe3b58cd.png">

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'paulahayes.sequentialedit_queueditems' doesn't exist in /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('DELETE FROM `se...')
#2 /Users/keithmancuso/Sites/paulahayes-craft/vendor/nilsenpaul/craft-sequentialedit/src/services/SequentialEditService.php(160): yii\db\Command->execute()
#3 /Users/keithmancuso/Sites/paulahayes-craft/vendor/nilsenpaul/craft-sequentialedit/src/SequentialEdit.php(80): nilsenpaul\sequentialedit\services\SequentialEditService::destroyQueueOnAnythingButEdits()
#4 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/BaseObject.php(109): nilsenpaul\sequentialedit\SequentialEdit->init()
#5 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#6 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/base/Plugin.php(113): yii\base\Module->__construct('sequential-edit', Object(craft\web\Application), Array)
#7 [internal function]: craft\base\Plugin->__construct('sequential-edit', Object(craft\web\Application), Array)
#8 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#9 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('nilsenpaul\\sequ...', Array, Array)
#10 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('nilsenpaul\\sequ...', Array, Array)
#11 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/services/Plugins.php(788): yii\BaseYii::createObject(Array, Array)
#12 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/services/Plugins.php(448): craft\services\Plugins->createPlugin('sequential-edit')
#13 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/controllers/PluginsController.php(48): craft\services\Plugins->installPlugin('sequential-edit')
#14 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#15 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('install-plugin', Array)
#18 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#19 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('plugins/install...', Array)
#20 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/web/Application.php(538): craft\web\Application->runAction('plugins/install...', Array)
#21 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /Users/keithmancuso/Sites/paulahayes-craft/web/index.php(21): yii\base\Application->run()
#24 /Users/keithmancuso/.composer/vendor/laravel/valet/server.php(147): require('/Users/keithman...')
#25 {main}

Next yii\db\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'paulahayes.sequentialedit_queueditems' doesn't exist
The SQL being executed was: DELETE FROM `sequentialedit_queueditems` WHERE `sessionId`='q1fs532ormshbei7g3tmk3v7ho' in /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `se...')
#1 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('DELETE FROM `se...')
#2 /Users/keithmancuso/Sites/paulahayes-craft/vendor/nilsenpaul/craft-sequentialedit/src/services/SequentialEditService.php(160): yii\db\Command->execute()
#3 /Users/keithmancuso/Sites/paulahayes-craft/vendor/nilsenpaul/craft-sequentialedit/src/SequentialEdit.php(80): nilsenpaul\sequentialedit\services\SequentialEditService::destroyQueueOnAnythingButEdits()
#4 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/BaseObject.php(109): nilsenpaul\sequentialedit\SequentialEdit->init()
#5 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#6 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/base/Plugin.php(113): yii\base\Module->__construct('sequential-edit', Object(craft\web\Application), Array)
#7 [internal function]: craft\base\Plugin->__construct('sequential-edit', Object(craft\web\Application), Array)
#8 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#9 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('nilsenpaul\\sequ...', Array, Array)
#10 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('nilsenpaul\\sequ...', Array, Array)
#11 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/services/Plugins.php(788): yii\BaseYii::createObject(Array, Array)
#12 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/services/Plugins.php(448): craft\services\Plugins->createPlugin('sequential-edit')
#13 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/controllers/PluginsController.php(48): craft\services\Plugins->installPlugin('sequential-edit')
#14 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#15 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('install-plugin', Array)
#18 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#19 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('plugins/install...', Array)
#20 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/web/Application.php(538): craft\web\Application->runAction('plugins/install...', Array)
#21 /Users/keithmancuso/Sites/paulahayes-craft/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /Users/keithmancuso/Sites/paulahayes-craft/web/index.php(21): yii\base\Application->run()
#24 /Users/keithmancuso/.composer/vendor/laravel/valet/server.php(147): require('/Users/keithman...')
#25 {main}
Additional Information:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'paulahayes.sequentialedit_queueditems' doesn't exist
)

Copy Stacktrace Search Stackoverflow Search Google Exception
Database Exception – yii\db\Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'paulahayes.sequentialedit_queueditems' doesn't exist
The SQL being executed was: DELETE FROM `sequentialedit_queueditems` WHERE `sessionId`='q1fs532ormshbei7g3tmk3v7ho'
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'paulahayes.sequentialedit_queueditems' doesn't exist
)
↵
Caused by: PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'paulahayes.sequentialedit_queueditems' doesn't exist
in /Users/keithmancuso/Sites/paulahayes-craft/vendor/yiisoft/yii2/db/Command.php at line 1258

**Comment by mannachurch** [comment]
I got the same error

**Comment by nilsenpaul** [comment]
Sorry for the inconvenience. Could you please update to the latest version and try again?

**Comment by nilsenpaul** [comment]
Fixed by https://github.com/nilsenpaul/craft-sequentialedit/commit/2de44013159445cd0a2d6192ee4e9f0df8ed9050. Thanks for pointing this out!
