### ISSUE TITLE
Sequential Edit does not work at all

### ISSUE THREAD

**Issue by outline4** [nilsenpaul/craft-sequentialedit#4]
Hi, 
I've upgraded a site from Craft v2 to Craft v3. 
They heavily depend on sequential editing. 

After the first save, instead of redirecting to the next entry, it redirects to the index page. 
When saving with cmd-s it stays on the same page. As if it wasn't installed (but the dropdown option is there).

PHP version | 7.2.21
Craft Pro 3.2.10
Sequential Edit | 1.0.8

Please help! 
Stefan

P.s. it's a multisite install

**Comment by nilsenpaul** [comment]
Stefan, we'll look into this!

**Comment by outline4** [comment]
Hi it's mid October and it's still not working and no update in sight?  
I mean, it's a paid plugin, if you can't support this thing I'd suggest you either make it free or drop it altogether...

**Comment by nilsenpaul** [comment]
You're absolutely right. We'll make it work. If I have any questions, I'll reach out to you!

**Comment by outline4** [comment]
Thanks! 
I am happy to test it…

**Comment by outline4** [comment]
Any news?

**Comment by nilsenpaul** [comment]
Hm no ... I dove into it, but can’t quite put my finger on the problem. Back on it on Wednesday, though!

**Comment by connorcowling** [comment]
In your description you mention assets, which is what I really needed.. however after buying the plugin you do not offer asset renaming??

**Comment by nilsenpaul** [comment]
@outline4 I'm deploying a fix to this bug as we speak.
@connorcowling Could you open a new issue?

**Comment by nilsenpaul** [comment]
This issue is fixed in 1.0.8.1. My apologies for the time it took!

**Comment by outline4** [comment]
Hi, 

I've just updated it, and it works sort of... it looses track after a few entries?  
I'm on Craft CMS 3.2.10.

hm?

**Comment by nilsenpaul** [comment]
Hm, sounds like a request that triggers the list to be cleared. I’ll get back on it!

**Comment by outline4** [comment]
Do I have to clear caches or do something else maybe?  
Happy to help.

**Comment by nilsenpaul** [comment]
@outline4 Just to be sure: did you have a second tab open in which you worked with the CP with the same session?

**Comment by outline4** [comment]
Hi Nils, 
Yes, I always have multiple tabs open when I am developing.  Sometimes it can be more than 10 tabs.

**Comment by outline4** [comment]
To be clear: I have other tabs open, but I was working only on one tab when the plugin suddenly forgets the next entries.  

e.g. I select 5 entries, and suddenly after 3 entries it will stuck on entry 3. Saving just reloads the same entry again and again.  

Also, I save the entries with cmd-s (not pressing the button)

It would be nice if the plugin could return to the index after editing all the entries.  At the moment it just sits on the last entry (if it gets to it) .

**Comment by outline4** [comment]
please hang in there! it's such a useful plugin.

**Comment by nilsenpaul** [comment]
@outline4 I can't seem to replicate this bug. With your debug toolbar's network panel open, do you see any requests happening after which it stops working? We have to find the edge case here ... The plugin listens to the events for saving an entry, and the event for applying a draft. I might've missed one there, so I'll start looking into that.

I think I'll make the 'return to X after final save' a plugin setting. Now, the plugin does nothing (thus allowing Craft's default "stay on edit page" behaviour). It would be nice to make that configurable. Could you add an issue for that?
