### ISSUE TITLE
No asset renaming

### ISSUE THREAD

**Issue by connorcowling** [nilsenpaul/craft-sequentialedit#5]
In your description you mention assets, which is what I really needed.. however after buying the plugin you do not offer asset renaming??

**Comment by nilsenpaul** [comment]
Hi @connorcowling, the plugin indeed does not offer sequentially editing assets. I removed that from the description in the version I just released, sorry for the inconvenience. I'd be happy to refund your purchase, let me know if you'd like that.

**Comment by connorcowling** [comment]
Yes please, thanks for the explanation

**Comment by nilsenpaul** [comment]
@connorcowling For your information, we've asked Pixel & Tonic how the refund process works. We'll keep you in the loop!

**Comment by connorcowling** [comment]
Thanks a lot

**Comment by nilsenpaul** [comment]
Refund is on its way.
